
zuul:
  ignored-services: '*'
  routes:
    inventory-service: /inventory/**
    basket-service: /basket/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


